# src/main/resources/application.yml
server:
  port: 8090

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/ms_thesis_service
    username: root
    password:

  datasource:
    url: jdbc:mysql://localhost:3306/ms_thesis_service
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/auth

logging:
  level:
    root: INFO
    com.upu.msthesisservice: DEBUG

spring:
  cloud:
    stream:
      bindings:
        thesisEvents-out-0:
          destination: thesis-topic
        input:
          destination: thesis-topic
          group: thesis-group
      kafka:
        binder:
          brokers: localhost:9092
