spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/ms_notification_service
    username: root
    password:

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO
    com.upu.msnotificationservice: DEBUG
