# ms-user-service.yml en el repositorio de configuración
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/ms_user_service
    username: root
    password: ""  # Sin contraseña para MySQL

logging:
  level:
    root: INFO
    com.upu.msuserservice: DEBUG
