# En el repositorio de configuración (e.g., C:/config-repo/ms-user-service.yml)
spring:
  application:
    name: ms-user-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/ms_user_service
    username: root
    password:

logging:
  level:
    root: INFO
    com.upu.microservice: DEBUG
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}