# src/main/resources/application.yml
server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/ms_user_service
    username: root
    password: ""  # No hay contraseña para la base de datos

logging:
  level:
    root: INFO
    com.upu.msuserservice: DEBUG
