# src/main/resources/application.yml
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_authentication_service
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    com.upu.msauthenticationservice: DEBUG
